--JOINS in SQL :

CREATE TABLE Employee3(employee_id SERIAL PRIMARY KEY,
	First_name VARCHAR(50),	
	Last_name VARCHAR(50),
	department_id INT
	);

INSERT INTO Employee3(First_name,Last_name,department_id) 
VALUES ('Rahul','Sharma',101),
('Priya','Mehta',102),
('Ankit','Verma',103),
('Simran','Kaur',NULL),
('Aman','Singh',101);

SELECT *FROM Employee3;

CREATE TABLE DEPARTMENTS (
	DEPARTMENT_ID INT PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(50)
);

INSERT INTO
	DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES
	(101, 'Sales'),
	(102, 'Marketing'),
	(103, 'IT'),
	(104, 'HR');

SELECT *FROM DEPARTMENTS;

--1)INNER JOIN 
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEE3 E
	INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--2)LEFT JOIN OR LEFT OUTER JOIN:
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEE3 E 
	LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--3)RIGHT JOIN OR RIGHT OUTER JOIN:
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEE3 E
	RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

