--JOINS IN SQL
--4)FULL OUTER JOIN
--5)CROSS JOIN 
--6)SELF JOIN
SELECT
	*
FROM
	EMPLOYEE3;

SELECT
	*
FROM
	DEPARTMENTS;

--4)FULL OUTER JOIN 
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_ID
FROM
	EMPLOYEE3 E
	FULL OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--5)CROSS JOIN 
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEE3 E
	CROSS JOIN DEPARTMENTS D;

--6)SELF JOIN 
SELECT
	E1.FIRST_NAME AS EMPLOYEE1,
	E2.FIRST_NAME AS EMPLOYEE2,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEE3 E1
	JOIN EMPLOYEE3 E2 ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
	AND E1.EMPLOYEE_ID != E2.EMPLOYEE_ID
	JOIN DEPARTMENTS D ON E1.DEPARTMENT_ID = D.DEPARTMENT_ID;

	